# Generated by Django 3.0.7 on 2022-04-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleshistory',
            old_name='extra_items',
            new_name='extra_items_set',
        ),
        migrations.RenameField(
            model_name='saleshistory',
            old_name='purchased_items',
            new_name='purchased_items_set',
        ),
    ]
