# Generated by Django 3.0.7 on 2022-04-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pis_sales', '0001_initial'),
        ('pis_retailer', '0001_initial'),
        ('pis_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_invoice', to='pis_sales.SalesHistory'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_ledger', to='pis_retailer.Retailer'),
        ),
    ]
